FROM python:3.10-slim

WORKDIR /app

# 1) Python bağımlılıkları
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2) Uygulama kodu
COPY app.py .

# 3) Eğitilmiş modeller ve tokenizer
COPY saved_model_n   saved_model_n
COPY saved_model_i   saved_model_i
COPY saved_tokenizer saved_tokenizer

# 4) Port ve başlatma
EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
